<?php

return [
    'hill' => [
        'page_title' => 'Hill Station Retreats | SHABDD TRAVEL',
        'meta_description' => 'Discover cool-climate retreats across Kashmir, Manali, Shimla, Munnar, Ooty, and Auli with scenic stays, smart filters, and premium mountain planning.',
        'palette' => [
            'ink' => '#1e3227',
            'muted' => 'rgba(30, 50, 39, 0.72)',
            'sand' => '#edf5ef',
            'mint' => '#d9eadd',
            'aqua' => '#4e8d63',
            'coral' => '#d58b45',
            'border' => 'rgba(30, 50, 39, 0.12)',
        ],
        'hero' => [
            'eyebrow' => 'Mountain escapes across India',
            'icon' => 'bi bi-mountain',
            'title' => 'Hill Station Retreats',
            'description' => 'From pine forests to snow valleys, this page brings together mountain holidays with slower pacing, scenic drives, and cozy stays that feel refreshing in every season.',
            'image' => 'images/himachal.jpg',
            'primary_action' => 'Explore Hill Destinations',
            'secondary_action' => 'View Mountain Packages',
        ],
        'destination_section' => [
            'eyebrow' => 'Hill station destinations',
            'title' => 'Filter hill destinations',
            'description' => 'Use destination, budget, duration, and travel style to narrow the mountain getaway grid.',
            'empty_title' => 'No hill destinations match your filters',
            'empty_description' => 'Try another destination, budget, duration, or travel style to see more mountain options.',
        ],
        'package_section' => [
            'eyebrow' => 'Popular hill packages',
            'title' => 'Popular hill station packages',
            'description' => 'A curated slider of the most relevant mountain packages for quick browsing.',
            'empty_title' => 'No hill packages yet',
            'empty_description' => 'Add mountain packages in the admin panel to populate this slider.',
        ],
        'benefits_section' => [
            'eyebrow' => 'Why choose hills',
            'title' => 'Built for scenic planning and comfort',
            'description' => 'These benefits help visitors feel confident about booking a cool-climate trip.',
        ],
        'testimonial_section' => [
            'eyebrow' => 'Traveler stories',
            'title' => 'Travelers love mountain holidays',
            'description' => 'Social proof that supports trust, comfort, and booking confidence.',
        ],
        'cta' => [
            'kicker' => 'Cool-climate planning made easy',
            'title' => 'Plan Your Perfect Hill Getaway Today',
            'description' => 'Tell us your dates, budget, and style. We will match you with the best mountain getaway for a trip that feels calm, scenic, and easy to book.',
        ],
        'faq_section' => [
            'eyebrow' => 'FAQs',
            'title' => 'Quick answers before you book',
            'description' => 'Clear, search-friendly answers that help travelers move toward the booking step.',
        ],
        'banner_slides' => [
            [
                'eyebrow' => 'Snowline spotlight',
                'icon' => 'bi bi-snow',
                'title' => 'Slow mornings, mountain views, and stays that warm up the trip.',
                'description' => 'Showcase a cozy hill holiday with warm hospitality, pine-lined roads, and moments that feel made for unwinding.',
                'image' => 'images/himachal.jpg',
            ],
            [
                'eyebrow' => 'Valley trail',
                'icon' => 'bi bi-tree-fill',
                'title' => 'Fresh air, quiet roads, and scenic stops that keep the pace gentle.',
                'description' => 'Highlight destinations where the journey matters as much as the stay, especially for couples and families.',
                'image' => 'images/kerala.avif',
            ],
            [
                'eyebrow' => 'Cool-weather escape',
                'icon' => 'bi bi-stars',
                'title' => 'Use a bold transition section to keep the page moving.',
                'description' => 'This banner helps break up the page and bridges the destination grid with the package slider below.',
                'image' => 'images/world-map.avif',
            ],
        ],
        'why_choose' => [
            [
                'icon' => 'bi bi-tree-fill',
                'title' => 'Altitude-aware planning',
                'text' => 'We match travel dates and routes to the season so mountain days feel easy, scenic, and comfortable.',
            ],
            [
                'icon' => 'bi bi-stars',
                'title' => 'Cosy stays',
                'text' => 'Handpicked cottages, resorts, and boutique stays that make the cool-climate vibe feel premium.',
            ],
            [
                'icon' => 'bi bi-truck',
                'title' => 'Smooth transfers',
                'text' => 'Airport pickups, scenic drives, and local movement planned so the trip stays relaxed from day one.',
            ],
            [
                'icon' => 'bi bi-shield-check',
                'title' => 'Trusted booking support',
                'text' => 'A clean booking process with responsive guidance before, during, and after travel.',
            ],
        ],
        'testimonials' => [
            [
                'name' => 'Aarav & Meera',
                'rating' => 5,
                'text' => 'Our hill holiday felt polished and easy. Great hotel choice, smooth transfers, and exactly the right pace for a mountain escape.',
            ],
            [
                'name' => 'Nisha R.',
                'rating' => 5,
                'text' => 'We booked Kashmir for our family and the itinerary made sense from start to finish. The scenic days were memorable and stress-free.',
            ],
            [
                'name' => 'Karan S.',
                'rating' => 5,
                'text' => 'The team helped us compare hill options and find a honeymoon-style escape that felt premium without being overcomplicated.',
            ],
        ],
        'faqs' => [
            [
                'question' => 'Which hill destination is best for first-time travelers?',
                'answer' => 'Manali is usually the easiest first choice because it combines scenic views, familiar transport options, and a strong mix of stays and activities.',
            ],
            [
                'question' => 'Which destination is best for honeymoon trips?',
                'answer' => 'Kashmir, Munnar, and Auli are strong choices for couples who want quiet stays, beautiful weather windows, and slower pacing.',
            ],
            [
                'question' => 'Can I find family-friendly hill packages here?',
                'answer' => 'Yes. Use the Family filter to find packages that suit relaxed sightseeing, comfortable stays, and easy transfers.',
            ],
            [
                'question' => 'Are snow activities available on hill trips?',
                'answer' => 'Yes. Hill holidays can include snow play, gondola rides, nature walks, local experiences, and winter sports depending on the destination.',
            ],
        ],
        'destinations' => [
            [
                'name' => 'Manali',
                'keywords' => ['Manali', 'Kasol', 'Solang'],
                'country' => 'India',
                'duration' => '4-5 Days',
                'price_from' => 22000,
                'rating' => 4.7,
                'travel_styles' => ['Honeymoon', 'Family', 'Adventure'],
                'description' => 'Snow views, pine forests, and a relaxed pace for quick mountain holidays.',
                'image' => 'images/himachal.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill', 'destination' => 'manali'],
            ],
            [
                'name' => 'Kashmir',
                'keywords' => ['Kashmir', 'Srinagar', 'Gulmarg'],
                'country' => 'India',
                'duration' => '5-7 Days',
                'price_from' => 38000,
                'rating' => 4.9,
                'travel_styles' => ['Honeymoon', 'Family', 'Nature'],
                'description' => 'Houseboats, valleys, and postcard mountain views with an elegant travel feel.',
                'image' => 'images/himachal.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill', 'destination' => 'kashmir'],
            ],
            [
                'name' => 'Shimla and Kufri',
                'keywords' => ['Shimla', 'Kufri'],
                'country' => 'India',
                'duration' => '3-5 Days',
                'price_from' => 19800,
                'rating' => 4.6,
                'travel_styles' => ['Family', 'Weekend', 'Couples'],
                'description' => 'Classic hill vibes with heritage walks, viewpoints, and easy family pacing.',
                'image' => 'images/himachal.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill', 'destination' => 'shimla'],
            ],
            [
                'name' => 'Munnar',
                'keywords' => ['Munnar'],
                'country' => 'India',
                'duration' => '4-6 Days',
                'price_from' => 26000,
                'rating' => 4.8,
                'travel_styles' => ['Honeymoon', 'Nature', 'Wellness'],
                'description' => 'Tea gardens, fresh air, and quiet resorts for a softer mountain escape.',
                'image' => 'images/kerala.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill', 'destination' => 'munnar'],
            ],
            [
                'name' => 'Ooty',
                'keywords' => ['Ooty'],
                'country' => 'India',
                'duration' => '3-5 Days',
                'price_from' => 21000,
                'rating' => 4.5,
                'travel_styles' => ['Family', 'Friends', 'Nature'],
                'description' => 'Tea estates, toy train nostalgia, and pleasant weather for easy holidays.',
                'image' => 'images/kerala.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill', 'destination' => 'ooty'],
            ],
            [
                'name' => 'Auli',
                'keywords' => ['Auli'],
                'country' => 'India',
                'duration' => '4-6 Days',
                'price_from' => 34000,
                'rating' => 4.7,
                'travel_styles' => ['Adventure', 'Luxury', 'Winter'],
                'description' => 'Ski slopes, sweeping mountain lines, and a premium winter holiday mood.',
                'image' => 'images/himachal.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill', 'destination' => 'auli'],
            ],
        ],
        'packages' => [
            [
                'keywords' => ['Manali'],
                'title' => 'Manali-Kasol Signature Escape',
                'country' => 'India',
                'location' => 'Manali, Himachal',
                'category' => 'Popular',
                'duration' => '5 Days',
                'price' => 28999,
                'rating' => 4.8,
                'theme' => 'Hill',
                'description' => 'A scenic mountain break with cozy stays, pine roads, and simple transfer planning.',
                'image' => 'images/himachal.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill'],
            ],
            [
                'keywords' => ['Kashmir'],
                'title' => 'Kashmir Valley Holiday',
                'country' => 'India',
                'location' => 'Srinagar, Kashmir',
                'category' => 'Popular',
                'duration' => '6 Days',
                'price' => 39999,
                'rating' => 5.0,
                'theme' => 'Hill',
                'description' => 'Houseboats, valley views, and a romantic pace tailored for couples and families.',
                'image' => 'images/himachal.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill'],
            ],
            [
                'keywords' => ['Shimla'],
                'title' => 'Shimla Heritage Weekend',
                'country' => 'India',
                'location' => 'Shimla, Himachal',
                'category' => 'Popular',
                'duration' => '4 Days',
                'price' => 21999,
                'rating' => 4.6,
                'theme' => 'Hill',
                'description' => 'A short classic hill break with viewpoint drives and old-town charm.',
                'image' => 'images/kerala.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill'],
            ],
            [
                'keywords' => ['Munnar'],
                'title' => 'Munnar Tea Trail Retreat',
                'country' => 'India',
                'location' => 'Munnar, Kerala',
                'category' => 'Popular',
                'duration' => '5 Days',
                'price' => 26999,
                'rating' => 4.8,
                'theme' => 'Hill',
                'description' => 'Tea estates, cool breezes, and wellness-forward stays for a slower rhythm.',
                'image' => 'images/kerala.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'hill'],
            ],
        ],
    ],
    'island' => [
        'page_title' => 'Island Getaways | SHABDD TRAVEL',
        'meta_description' => 'Discover island escapes across Andaman, Lakshadweep, Bali, Maldives, Phuket, and Krabi with green, tropical styling and premium getaway planning.',
        'palette' => [
            'ink' => '#113d34',
            'muted' => 'rgba(17, 61, 52, 0.72)',
            'sand' => '#edf9f1',
            'mint' => '#d0f3df',
            'aqua' => '#19a874',
            'coral' => '#4fc77d',
            'border' => 'rgba(17, 61, 52, 0.12)',
        ],
        'hero' => [
            'eyebrow' => 'Island escapes with a tropical feel',
            'icon' => 'bi bi-droplet-half',
            'title' => 'Island Getaways',
            'description' => 'Plan breezy island escapes with turquoise water, coral shores, and slow scenic days. From Andaman and Lakshadweep to Bali and Maldives, this page is built for effortless island dreaming.',
            'image' => 'images/kerala.avif',
            'primary_action' => 'Explore Island Destinations',
            'secondary_action' => 'View Island Packages',
        ],
        'destination_section' => [
            'eyebrow' => 'Island destinations',
            'title' => 'Filter island destinations',
            'description' => 'Use destination, budget, duration, and travel style to narrow the island getaway grid.',
            'empty_title' => 'No island destinations match your filters',
            'empty_description' => 'Try another destination, budget, duration, or travel style to see more island options.',
        ],
        'package_section' => [
            'eyebrow' => 'Popular island packages',
            'title' => 'Popular island getaway packages',
            'description' => 'A curated slider of the most relevant island packages for quick browsing.',
            'empty_title' => 'No island packages yet',
            'empty_description' => 'Add island packages in the admin panel to populate this slider.',
        ],
        'benefits_section' => [
            'eyebrow' => 'Why choose islands',
            'title' => 'Built for easy island planning',
            'description' => 'These benefits help visitors feel confident about booking a tropical trip.',
        ],
        'testimonial_section' => [
            'eyebrow' => 'Traveler stories',
            'title' => 'Travelers love island holidays',
            'description' => 'Social proof that supports trust, comfort, and booking confidence.',
        ],
        'cta' => [
            'kicker' => 'Tropical planning made easy',
            'title' => 'Plan Your Perfect Island Getaway Today',
            'description' => 'Tell us your dates, budget, and style. We will match you with the best island break for a trip that feels refreshing, scenic, and easy to book.',
        ],
        'faq_section' => [
            'eyebrow' => 'FAQs',
            'title' => 'Quick answers before you book',
            'description' => 'Clear, search-friendly answers that help travelers move toward the booking step.',
        ],
        'banner_slides' => [
            [
                'eyebrow' => 'Tropical spotlight',
                'icon' => 'bi bi-water',
                'title' => 'Soft waves, clear skies, and stays that feel made for slowing down.',
                'description' => 'Showcase a tropical holiday with warm hospitality, island transfers, and the kind of scenery that makes the trip feel complete.',
                'image' => 'images/kerala.avif',
            ],
            [
                'eyebrow' => 'Coral coast',
                'icon' => 'bi bi-sun',
                'title' => 'Refresh the page with a bright banner between the filters and the package slider.',
                'description' => 'This visual break helps the island experience feel airy, premium, and easy to browse.',
                'image' => 'images/world-map.avif',
            ],
            [
                'eyebrow' => 'Lagoon mood',
                'icon' => 'bi bi-stars',
                'title' => 'Use a bold transition section to keep the page moving.',
                'description' => 'Feature your strongest island offer before visitors scroll into the package cards below.',
                'image' => 'images/couple-bg.jpg',
            ],
        ],
        'why_choose' => [
            [
                'icon' => 'bi bi-water',
                'title' => 'Island transfer support',
                'text' => 'We coordinate ferries, speedboats, and airport transfers so the journey stays smooth from the start.',
            ],
            [
                'icon' => 'bi bi-stars',
                'title' => 'Tropical stays',
                'text' => 'Handpicked resorts, beach villas, and boutique hideaways that bring a calm, premium feel.',
            ],
            [
                'icon' => 'bi bi-heart',
                'title' => 'Couple-first planning',
                'text' => 'We keep romance, privacy, and relaxed pacing at the center of every island itinerary.',
            ],
            [
                'icon' => 'bi bi-shield-check',
                'title' => 'Trusted booking support',
                'text' => 'A simple booking process with responsive support before, during, and after travel.',
            ],
        ],
        'testimonials' => [
            [
                'name' => 'Aarav & Nisha',
                'rating' => 5,
                'text' => 'Our island holiday felt effortless. Great stay selection, smooth transfers, and the perfect pace for a tropical break.',
            ],
            [
                'name' => 'Meera R.',
                'rating' => 5,
                'text' => 'We booked Andaman for our family and the itinerary was peaceful, easy to understand, and beautiful from day one.',
            ],
            [
                'name' => 'Karan S.',
                'rating' => 5,
                'text' => 'The team helped us compare island options and find a premium escape that matched our budget and travel style.',
            ],
        ],
        'faqs' => [
            [
                'question' => 'Which island destination is best for first-time travelers?',
                'answer' => 'Andaman is usually the easiest first choice because it combines beautiful beaches, clear logistics, and a strong mix of activities and stays.',
            ],
            [
                'question' => 'Which destination is best for honeymoon trips?',
                'answer' => 'Lakshadweep, Maldives, and Bali are strong choices for couples who want quieter stays, scenic water, and more privacy.',
            ],
            [
                'question' => 'Can I find family-friendly island packages here?',
                'answer' => 'Yes. Use the Family filter to find packages that suit relaxed sightseeing, comfortable stays, and easy transfers.',
            ],
            [
                'question' => 'Are water activities available on island trips?',
                'answer' => 'Yes. Island holidays can include snorkeling, scuba, kayaking, ferry hopping, sunset cruises, and beach time depending on the destination.',
            ],
        ],
        'destinations' => [
            [
                'name' => 'Andaman Islands',
                'keywords' => ['Andaman', 'Port Blair', 'Havelock'],
                'country' => 'India',
                'duration' => '4-6 Days',
                'price_from' => 45000,
                'rating' => 4.9,
                'travel_styles' => ['Honeymoon', 'Family', 'Water Activities'],
                'description' => 'Blue water, coral beaches, and a calm island pace for memorable holidays.',
                'image' => 'images/kerala.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island', 'destination' => 'andaman'],
            ],
            [
                'name' => 'Lakshadweep',
                'keywords' => ['Lakshadweep'],
                'country' => 'India',
                'duration' => '4-6 Days',
                'price_from' => 58000,
                'rating' => 5.0,
                'travel_styles' => ['Honeymoon', 'Luxury', 'Beach'],
                'description' => 'Lagoon waters, quiet islands, and a premium private-island atmosphere.',
                'image' => 'images/kerala.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island', 'destination' => 'lakshadweep'],
            ],
            [
                'name' => 'Bali',
                'keywords' => ['Bali'],
                'country' => 'Indonesia',
                'duration' => '5-7 Days',
                'price_from' => 52000,
                'rating' => 4.8,
                'travel_styles' => ['Friends', 'Wellness', 'Honeymoon'],
                'description' => 'Temples, waterfalls, and island charm with a flexible mix of experiences.',
                'image' => 'images/world-map.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island', 'destination' => 'bali'],
            ],
            [
                'name' => 'Maldives',
                'keywords' => ['Maldives'],
                'country' => 'Maldives',
                'duration' => '4-6 Days',
                'price_from' => 135000,
                'rating' => 5.0,
                'travel_styles' => ['Honeymoon', 'Luxury', 'Overwater'],
                'description' => 'Overwater villas, turquoise lagoons, and a polished honeymoon feel.',
                'image' => 'images/couple-bg.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island', 'destination' => 'maldives'],
            ],
            [
                'name' => 'Phuket',
                'keywords' => ['Phuket'],
                'country' => 'Thailand',
                'duration' => '5-7 Days',
                'price_from' => 60000,
                'rating' => 4.7,
                'travel_styles' => ['Friends', 'Island Hopping', 'Nightlife'],
                'description' => 'Island-hopping, beaches, and a lively trip for groups and friends.',
                'image' => 'images/world-map.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island', 'destination' => 'phuket'],
            ],
            [
                'name' => 'Krabi',
                'keywords' => ['Krabi'],
                'country' => 'Thailand',
                'duration' => '4-6 Days',
                'price_from' => 55000,
                'rating' => 4.7,
                'travel_styles' => ['Family', 'Adventure', 'Kayaking'],
                'description' => 'Soft beaches, scenic limestone cliffs, and a relaxed adventure vibe.',
                'image' => 'images/world-map.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island', 'destination' => 'krabi'],
            ],
        ],
        'packages' => [
            [
                'keywords' => ['Andaman'],
                'title' => 'Andaman Island Discovery',
                'country' => 'India',
                'location' => 'Andaman Islands',
                'category' => 'Popular',
                'duration' => '5 Days',
                'price' => 48999,
                'rating' => 4.9,
                'theme' => 'Island',
                'description' => 'Beach time, water activities, and easy transfers with a tropical mood.',
                'image' => 'images/kerala.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island'],
            ],
            [
                'keywords' => ['Lakshadweep'],
                'title' => 'Lakshadweep Lagoon Escape',
                'country' => 'India',
                'location' => 'Lakshadweep',
                'category' => 'Popular',
                'duration' => '5 Days',
                'price' => 62999,
                'rating' => 5.0,
                'theme' => 'Island',
                'description' => 'Quiet lagoons, boutique stays, and a premium island-only feel.',
                'image' => 'images/kerala.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island'],
            ],
            [
                'keywords' => ['Bali'],
                'title' => 'Bali Island Escape',
                'country' => 'Indonesia',
                'location' => 'Bali',
                'category' => 'Popular',
                'duration' => '6 Days',
                'price' => 56999,
                'rating' => 4.8,
                'theme' => 'Island',
                'description' => 'Jungle, temples, and beaches with a balanced island itinerary.',
                'image' => 'images/world-map.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island'],
            ],
            [
                'keywords' => ['Maldives'],
                'title' => 'Maldives Honeymoon Hideaway',
                'country' => 'Maldives',
                'location' => 'Maldives',
                'category' => 'Popular',
                'duration' => '5 Days',
                'price' => 145999,
                'rating' => 5.0,
                'theme' => 'Island',
                'description' => 'Overwater stays, private dining, and a polished romantic getaway.',
                'image' => 'images/couple-bg.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'island'],
            ],
        ],
    ],
    'desert' => [
        'page_title' => 'Desert Adventures | SHABDD TRAVEL',
        'meta_description' => 'Discover desert escapes across Dubai, Jaisalmer, Abu Dhabi, Rajasthan, Wadi Rum, and Sahara-inspired stays with warm tones and adventure-led planning.',
        'palette' => [
            'ink' => '#6a3f1a',
            'muted' => 'rgba(106, 63, 26, 0.72)',
            'sand' => '#f7ebdb',
            'mint' => '#f0d7b2',
            'aqua' => '#c97f32',
            'coral' => '#e09a46',
            'border' => 'rgba(106, 63, 26, 0.12)',
        ],
        'hero' => [
            'eyebrow' => 'Golden dunes and city lights',
            'icon' => 'bi bi-brightness-high',
            'title' => 'Desert Adventures',
            'description' => 'Chase golden dunes, fortress stays, and sunset safaris across Dubai, Jaisalmer, Abu Dhabi, and beyond. This page blends adventure with style, comfort, and classic desert experiences.',
            'image' => 'images/dubai.jpg',
            'primary_action' => 'Explore Desert Destinations',
            'secondary_action' => 'View Desert Packages',
        ],
        'destination_section' => [
            'eyebrow' => 'Desert destinations',
            'title' => 'Filter desert destinations',
            'description' => 'Use destination, budget, duration, and travel style to narrow the desert adventure grid.',
            'empty_title' => 'No desert destinations match your filters',
            'empty_description' => 'Try another destination, budget, duration, or travel style to see more desert options.',
        ],
        'package_section' => [
            'eyebrow' => 'Popular desert packages',
            'title' => 'Popular desert adventure packages',
            'description' => 'A curated slider of the most relevant desert packages for quick browsing.',
            'empty_title' => 'No desert packages yet',
            'empty_description' => 'Add desert packages in the admin panel to populate this slider.',
        ],
        'benefits_section' => [
            'eyebrow' => 'Why choose deserts',
            'title' => 'Built for adventure and comfort',
            'description' => 'These benefits help visitors feel confident about booking a desert trip.',
        ],
        'testimonial_section' => [
            'eyebrow' => 'Traveler stories',
            'title' => 'Travelers love desert holidays',
            'description' => 'Social proof that supports trust, comfort, and booking confidence.',
        ],
        'cta' => [
            'kicker' => 'Warm-weather planning made easy',
            'title' => 'Plan Your Perfect Desert Adventure Today',
            'description' => 'Tell us your dates, budget, and style. We will match you with the best desert escape for a trip that feels bold, scenic, and easy to book.',
        ],
        'faq_section' => [
            'eyebrow' => 'FAQs',
            'title' => 'Quick answers before you book',
            'description' => 'Clear, search-friendly answers that help travelers move toward the booking step.',
        ],
        'banner_slides' => [
            [
                'eyebrow' => 'Dune safari spotlight',
                'icon' => 'bi bi-truck-front-fill',
                'title' => 'Golden sands, sunset drives, and stays that bring the adventure together.',
                'description' => 'Showcase a desert holiday with bold scenery, warm evenings, and polished transfer planning.',
                'image' => 'images/dubai.jpg',
            ],
            [
                'eyebrow' => 'Fort city mood',
                'icon' => 'bi bi-building',
                'title' => 'Blend heritage, luxury, and desert energy in a banner that feels premium.',
                'description' => 'This section creates a strong visual bridge between the filters and the package slider below.',
                'image' => 'images/world-map.avif',
            ],
            [
                'eyebrow' => 'Evening glow',
                'icon' => 'bi bi-stars',
                'title' => 'Use a bold transition section to keep the page moving.',
                'description' => 'Feature your strongest desert offer before visitors scroll into the package cards below.',
                'image' => 'images/contact-us-bg.jpg',
            ],
        ],
        'why_choose' => [
            [
                'icon' => 'bi bi-truck-front-fill',
                'title' => 'Desert safari planning',
                'text' => 'We time safari runs, dune drives, and sunset stops so the experience feels smooth and memorable.',
            ],
            [
                'icon' => 'bi bi-stars',
                'title' => 'Iconic stays',
                'text' => 'Handpicked desert resorts, fortress hotels, and camp experiences that feel premium and atmospheric.',
            ],
            [
                'icon' => 'bi bi-compass',
                'title' => 'Adventure-forward routing',
                'text' => 'We combine city highlights, dune experiences, and cultural stops into a balanced desert plan.',
            ],
            [
                'icon' => 'bi bi-shield-check',
                'title' => 'Trusted booking support',
                'text' => 'A clean booking process with responsive guidance before, during, and after travel.',
            ],
        ],
        'testimonials' => [
            [
                'name' => 'Aarav & Meera',
                'rating' => 5,
                'text' => 'Our desert holiday felt polished and easy. Great hotel choice, smooth transfers, and exactly the right pace for an adventure break.',
            ],
            [
                'name' => 'Nisha R.',
                'rating' => 5,
                'text' => 'We booked a desert trip for our family and the itinerary made sense from start to finish. The dune days were memorable and stress-free.',
            ],
            [
                'name' => 'Karan S.',
                'rating' => 5,
                'text' => 'The team helped us compare desert options and find a premium escape that felt strong on value and easy to book.',
            ],
        ],
        'faqs' => [
            [
                'question' => 'Which desert destination is best for first-time travelers?',
                'answer' => 'Dubai is usually the easiest first choice because it combines desert adventures, city comfort, and a wide range of stays and activities.',
            ],
            [
                'question' => 'Which destination is best for honeymoon trips?',
                'answer' => 'Jaisalmer, Dubai, and Wadi Rum are strong choices for couples who want dramatic scenery, romantic stays, and memorable evenings.',
            ],
            [
                'question' => 'Can I find family-friendly desert packages here?',
                'answer' => 'Yes. Use the Family filter to find packages that suit relaxed sightseeing, comfortable stays, and easy transfers.',
            ],
            [
                'question' => 'Are adventure activities available on desert trips?',
                'answer' => 'Yes. Desert holidays can include dune bashing, camel rides, cultural evenings, heritage walks, and sunset safaris depending on the destination.',
            ],
        ],
        'destinations' => [
            [
                'name' => 'Dubai Desert Safari',
                'keywords' => ['Dubai', 'Desert Safari'],
                'country' => 'UAE',
                'duration' => '3-5 Days',
                'price_from' => 62000,
                'rating' => 4.8,
                'travel_styles' => ['Family', 'Luxury', 'Adventure'],
                'description' => 'Modern city comfort paired with dunes, skyline views, and classic safari moments.',
                'image' => 'images/dubai.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert', 'destination' => 'dubai'],
            ],
            [
                'name' => 'Jaisalmer',
                'keywords' => ['Jaisalmer', 'Rajasthan'],
                'country' => 'India',
                'duration' => '3-5 Days',
                'price_from' => 26000,
                'rating' => 4.7,
                'travel_styles' => ['Heritage', 'Family', 'Friends'],
                'description' => 'Fort views, desert camps, and warm cultural evenings with plenty of atmosphere.',
                'image' => 'images/dubai.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert', 'destination' => 'jaisalmer'],
            ],
            [
                'name' => 'Abu Dhabi Dunes',
                'keywords' => ['Abu Dhabi'],
                'country' => 'UAE',
                'duration' => '4-6 Days',
                'price_from' => 75000,
                'rating' => 4.8,
                'travel_styles' => ['Luxury', 'Couples', 'Adventure'],
                'description' => 'High-comfort city stays with dune experiences and polished evening plans.',
                'image' => 'images/dubai.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert', 'destination' => 'abu-dhabi'],
            ],
            [
                'name' => 'Rajasthan Desert Circuit',
                'keywords' => ['Rajasthan', 'Jodhpur', 'Jaisalmer'],
                'country' => 'India',
                'duration' => '5-7 Days',
                'price_from' => 32000,
                'rating' => 4.6,
                'travel_styles' => ['Heritage', 'Family', 'Culture'],
                'description' => 'Palaces, forts, and sand-side stays for a classic desert circuit with depth.',
                'image' => 'images/world-map.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert', 'destination' => 'rajasthan'],
            ],
            [
                'name' => 'Wadi Rum',
                'keywords' => ['Wadi Rum'],
                'country' => 'Jordan',
                'duration' => '4-6 Days',
                'price_from' => 98000,
                'rating' => 4.9,
                'travel_styles' => ['Adventure', 'Luxury', 'Photography'],
                'description' => 'Cinematic red sands, stargazing camps, and an iconic desert mood.',
                'image' => 'images/world-map.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert', 'destination' => 'wadi-rum'],
            ],
            [
                'name' => 'Sahara Camp',
                'keywords' => ['Sahara', 'Morocco'],
                'country' => 'Morocco',
                'duration' => '5-7 Days',
                'price_from' => 115000,
                'rating' => 4.8,
                'travel_styles' => ['Luxury', 'Adventure', 'Honeymoon'],
                'description' => 'Golden dunes, campfire evenings, and a dramatic desert experience.',
                'image' => 'images/contact-us-bg.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert', 'destination' => 'sahara'],
            ],
        ],
        'packages' => [
            [
                'keywords' => ['Dubai'],
                'title' => 'Dubai Desert Luxe',
                'country' => 'UAE',
                'location' => 'Dubai',
                'category' => 'Popular',
                'duration' => '4 Days',
                'price' => 65999,
                'rating' => 4.8,
                'theme' => 'Desert',
                'description' => 'A premium desert-city blend with skyline moments and dune highlights.',
                'image' => 'images/dubai.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert'],
            ],
            [
                'keywords' => ['Jaisalmer'],
                'title' => 'Jaisalmer Golden Dunes',
                'country' => 'India',
                'location' => 'Jaisalmer, Rajasthan',
                'category' => 'Popular',
                'duration' => '5 Days',
                'price' => 29999,
                'rating' => 4.7,
                'theme' => 'Desert',
                'description' => 'Fort views, camel rides, and a classic desert camp experience.',
                'image' => 'images/dubai.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert'],
            ],
            [
                'keywords' => ['Abu Dhabi'],
                'title' => 'Abu Dhabi Dune Retreat',
                'country' => 'UAE',
                'location' => 'Abu Dhabi',
                'category' => 'Popular',
                'duration' => '5 Days',
                'price' => 78999,
                'rating' => 4.8,
                'theme' => 'Desert',
                'description' => 'Luxury stays, dune drives, and a polished city-desert balance.',
                'image' => 'images/dubai.jpg',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert'],
            ],
            [
                'keywords' => ['Wadi Rum'],
                'title' => 'Wadi Rum Stargazing Escape',
                'country' => 'Jordan',
                'location' => 'Wadi Rum',
                'category' => 'Popular',
                'duration' => '6 Days',
                'price' => 99999,
                'rating' => 4.9,
                'theme' => 'Desert',
                'description' => 'Red sands, premium camp nights, and unforgettable night skies.',
                'image' => 'images/world-map.avif',
                'url_route' => 'packages.index',
                'url_params' => ['theme' => 'desert'],
            ],
        ],
    ],
];
